# TODO: methods for obtaining and plotting dose distribution


#TODO: GET BLOCK MATRIX-->GEOMETRIC DOMAIN MAPPING
#TODO: CALC y=Ax
#TODO: y TO FULL DOMAIN
#TODO: RESHAPE y AS VOLUME
#TODO: QUERY SLICES OF y, GENERATE DOSE WASH
#TODO: DOSE WASH METHOD
#TODO: SERVE DOSE WASH BASED ON VIEW, SLICE INDEX
#TODO: GET VOLUME DIMENSION INFO
#TODO: SEND VOL DIM INFO TO CLIENT (DOSE VIEWER)
#TODO: SERVE png OF CT IMAGES
#TODO: SERVE DATA TO GOOGLE GEOCHART OF COUNTOURS OF REQUESTED SLICE