from conrad.compat import *

WEIGHT_PWL_UNDER_DEFAULT = 1.
WEIGHT_PWL_OVER_DEFAULT = 0.05
WEIGHT_HINGE_DEFAULT = 1.
WEIGHT_LIN_NONTARGET_DEFAULT = 0.03
WEIGHT_QUAD_UNDER_DEFAULT = 0.5
WEIGHT_QUAD_OVER_DEFAULT = 1.
WEIGHT_EXP_OVER_DEFAULT = 1.