---
data_schemas:
- type : vector 
  data :
    file : <file_or_archive_path> 
    key : <key_for_archive>

- type : dense matrix
  layout :
  row_major : No
  data :
    file : <file_or_archive_path> 
    key : <key_for_archive>

- type : sparse matrix
  layout :
    CSR : No
    fortran_indexing : No
  shape : <tuple>
  data :
    pointers :
      file : <file_or_archive_path> 
      key : <key_for_archive>
    indices :
      file : <file_or_archive_path> 
      key : <key_for_archive>
    values :
      file : <file_or_archive_path> 
      key : <key_for_archive>

---
case_schema:
  case :
    name : CASE NAME

    voxel_grid :
      x : 100
      y : 80
      z : 70
      voxel_mask : /path/to/mask/file

    beams :
      type : apertures
      control_points :
        number : 360
        groups : 4
        group_sizes : [90, 90, 90, 90]
      max : 4.0
      max_active : No
      adjacency_matrix: <matrix_schema_placeholder> 

    frames :
      - name: geometric
        m : 1395870
        n : 360
        dir : /path/containing/data/
        dose_matrix : <matrix_schema_placeholder>
        voxel_labels : <vector_schema_placeholder>
        voxel_weights : null
        beam_labels : null
        beam_weights : null
        mappings : null

     # dose matrix with rows in arbitrary order, all-zero rows pruned if dense
      - name: full 
        m : 
        n : 
        dir :
        dose_matrix : <matrix_schema_placeholder>
        voxel_labels : <vector_schema_placeholder>
        voxel_weights : null
        beam_labels : null
        beam_weights : null
        mappings :
          - source : geometric
            target : self
            voxels : filename.npy
            beams : null

      - name : collapsed 
        m : 
        n : 
        dir : /path/containing/data/
        dose_matrix :
          layout :
            dense : Yes
            column_major : No
            fortran_indexing : No
          pointers : 
          indices : 
          data :
        voxel_labels :
        voxel_weights : 
        beam_labels :
        beam_weights :
        mappings :
          - source : full
            target : self
            voxels : filename.npy
            beams : null

    caches :
      - frame : collapsed
        dir : /path/to/matrix/cache/
        solver : POGS 
        left_preconditioner : <vector_schema_placeholder>      
        matrix : <matrix_schema_placeholder>      
        right_preconditioner : <vector_schema_placeholder>  
        projector :
          type : cholesky(identity + gramian)
          matrix : <matrix_schema_placeholder>  

    solutions : <history_schema_placeholder>
    prescription : <prescription_schema_placeholder>

---
history_schema:
  solutions :
  - name : reference
    frame : full
    x : <vector_schema_placeholder> 
    y : 
    mu : 
    nu : 
   
--- 
prescription_schema:
  prescription:
  - name : Target name
    label : <target label, integer> # e.g., 3
    target : Yes
    rx : <target dose, <float> [centi]Gray> # e.g., 35 Gy 
    constraints : <constraint list> # e.g., D80 > 32 Gy

  - name : Non-target name
    label : <>
    target : Yes
    rx : 60.0
    constraints :

  - name : PTV L Frontal
    label : 22
    target : Yes
    rx : 60.0
    constraints :

  - name : Eye L
    label : 2
    target : No
    constraints :

  - name : Lens L
    label : 3
    target : No
    constraints :

  - name : Brainstem
    label : 4
    target : No
    constraints :

  - name : Spinal Canal
    label : 5
    target : No
    constraints :

  - name : Parotid L
    label : 6
    target : No
    constraints :

  - name : Submandibular L
    label : 7
    target : No
    constraints :

  - name : Cochlea R
    label : 8
    target : No
    constraints :

  - name : Larynx
    label : 9
    target : No
    constraints :

  - name : Oral Cavity
    label : 10
    target : No
    constraints :

  - name : Brain
    label : 11
    target : No
    constraints :

  - name : Optic Nerve L
    label : 24
    target : No
    constraints :

  - name : Optic Chiasm
    label : 25
    target : No
    constraints :

  - name : Cord
    label : 29
    target : No
    constraints :

  - name : Body
    label : 0
    target : No
    constraints : 
